# Generated by Django 4.1.5 on 2023-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_what_we_do_options_alter_what_we_do_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='what_we_do',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
