# Generated by Django 4.1.5 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_about_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_we_do',
            name='is_active',
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='what_we_do',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
