# Generated by Django 4.1.5 on 2023-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='Education')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('icon', models.FileField(blank=True, upload_to='icon/Education')),
                ('icon_title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('icon', models.FileField(blank=True, upload_to='interviews')),
                ('icon_title', models.CharField(blank=True, max_length=500)),
                ('hyperlink', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Interviews',
            },
        ),
    ]
