# Generated by Django 4.1.5 on 2023-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
