# Generated by Django 4.1.5 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_center', '0002_education_hyperlink_education_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='interviews',
            name='is_active',
        ),
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='interviews',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
