# Generated by Django 4.1.5 on 2023-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, max_length=400)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
