# Generated by Django 4.1.5 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contact_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
