# Generated by Django 4.1.5 on 2023-01-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='photo/Header')),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Header logo',
            },
        ),
        migrations.CreateModel(
            name='Header_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Header Menu',
            },
        ),
    ]
