# Generated by Django 4.1.5 on 2023-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_logo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='header_menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
