# Generated by Django 4.1.5 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0002_header_logo_is_active_header_menu_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_logo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='header_menu',
            name='is_active',
        ),
        migrations.AddField(
            model_name='header_logo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='header_menu',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
