# Generated by Django 4.1.5 on 2023-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bharat_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media_center')),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Media Center',
            },
        ),
        migrations.CreateModel(
            name='Our_focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='our_focus')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Our focus',
            },
        ),
        migrations.CreateModel(
            name='Our_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='our_members')),
            ],
            options={
                'verbose_name_plural': 'Our members',
            },
        ),
        migrations.CreateModel(
            name='Our_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='our_vision')),
                ('button', models.CharField(blank=True, max_length=300)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Our vision',
            },
        ),
    ]
