# Generated by Django 4.1.5 on 2023-01-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bharat_dashboard', '0003_bannerimage_is_active_media_center_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='photo/Press-release')),
            ],
            options={
                'verbose_name_plural': 'Press Release Image',
            },
        ),
        migrations.CreateModel(
            name='press_release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='photo/Press-release')),
                ('title', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Press Release ',
            },
        ),
    ]
