# Generated by Django 4.1.5 on 2023-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bharat_dashboard', '0006_press_release_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='press_image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
