# Generated by Django 4.1.5 on 2023-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bharat_dashboard', '0007_press_image_is_active_press_release_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], max_length=100),
        ),
    ]
