# Generated by Django 4.1.5 on 2023-01-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bharat_dashboard', '0012_alter_bannerimage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_center',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='our_focus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='our_members',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='our_vision',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='press_image',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='press_release',
            name='is_active',
        ),
        migrations.AddField(
            model_name='media_center',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='our_focus',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='our_members',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='our_vision',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='press_image',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='press_release',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
